Loading rhel8/default-icl
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 intel/compilers/2020.2 intel/mkl/2020.2 intel/impi/2020.2/intel
    intel/libs/idb/2020.2 intel/libs/tbb/2020.2 intel/libs/ipp/2020.2
    intel/libs/daal/2020.2 intel/bundles/complib/2020.2
WARNING: Logging before flag parsing goes to stderr.
W0518 13:45:13.008736 23221526295424 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-18 13:45:21,590	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_13-45-21_589906_942388/logs.
2022-05-18 13:45:21,742	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:38690 to respond...
2022-05-18 13:45:22,744	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-18 13:45:22,744	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:38690 to respond...
2022-05-18 13:45:22,859	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:50861 to respond...
2022-05-18 13:45:22,860	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-18 13:45:22,907	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_13-45-21_589906_942388/logs.
2022-05-18 13:45:22,908	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-18 13:45:22,908	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2022-05-18 13:45:23,837	INFO tune.py:65 -- Did not find checkpoint file in ./ray_mopo/HalfCheetah/halfcheetah_mixed_capabilities_101e3.
2022-05-18 13:45:23,837	INFO tune.py:232 -- Starting a new experiment.
W0518 13:45:23.856490 23221526295424 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0518 13:45:23.856720 23221526295424 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-18 13:45:23,928	ERROR trial_runner.py:291 -- Trial Runner checkpointing failed.
Traceback (most recent call last):
  File "/rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 289, in step
    self.checkpoint()
  File "/rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 188, in checkpoint
    TrialRunner.CKPT_FILE_TMPL.format(self._session_str)))
FileNotFoundError: [Errno 2] No such file or directory: './ray_mopo/HalfCheetah/halfcheetah_mixed_capabilities_101e3/.tmp_checkpoint' -> './ray_mopo/HalfCheetah/halfcheetah_mixed_capabilities_101e3/experiment_state-2022-05-18_13-45-23.json'
W0518 14:00:45.942041 23221526295424 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-18 14:07:04,866	WARNING util.py:64 -- The `save_to_disk` operation took 1.2666349411010742 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:07:04,871	WARNING util.py:64 -- The `process_trial` operation took 1.2769269943237305 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:08:29,077	WARNING util.py:64 -- The `process_trial` operation took 0.1386241912841797 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:14:06,202	WARNING util.py:64 -- The `save_to_disk` operation took 0.4144020080566406 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:14:06,203	WARNING util.py:64 -- The `process_trial` operation took 0.4215281009674072 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:21:07,616	WARNING util.py:64 -- The `save_to_disk` operation took 0.37904858589172363 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:21:07,618	WARNING util.py:64 -- The `process_trial` operation took 0.38705921173095703 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:28:10,184	WARNING util.py:64 -- The `save_to_disk` operation took 0.4312708377838135 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:28:10,191	WARNING util.py:64 -- The `process_trial` operation took 0.4431779384613037 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:35:13,326	WARNING util.py:64 -- The `save_to_disk` operation took 0.43473362922668457 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:35:13,329	WARNING util.py:64 -- The `process_trial` operation took 0.4461953639984131 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:42:16,764	WARNING util.py:64 -- The `save_to_disk` operation took 0.43287158012390137 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:42:16,765	WARNING util.py:64 -- The `process_trial` operation took 0.43994784355163574 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:48:37,800	WARNING util.py:64 -- The `experiment_checkpoint` operation took 0.12134671211242676 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:49:20,427	WARNING util.py:64 -- The `save_to_disk` operation took 0.4795072078704834 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:49:20,428	WARNING util.py:64 -- The `process_trial` operation took 0.48645925521850586 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:56:21,994	WARNING util.py:64 -- The `save_to_disk` operation took 0.6656708717346191 seconds to complete, which may be a performance bottleneck.
2022-05-18 14:56:21,997	WARNING util.py:64 -- The `process_trial` operation took 0.6743576526641846 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:03:21,569	WARNING util.py:64 -- The `save_to_disk` operation took 0.4548957347869873 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:03:21,571	WARNING util.py:64 -- The `process_trial` operation took 0.4620189666748047 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:10:25,250	WARNING util.py:64 -- The `save_to_disk` operation took 0.431779146194458 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:10:25,264	WARNING util.py:64 -- The `process_trial` operation took 0.4516434669494629 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61327370 ON cpu-q-254 CANCELLED AT 2022-05-18T15:12:21 ***
