Can't load '/usr/local/software/slurm/slurm-20.11.9-rhel8/lib64/perl5/auto/Slurm/Slurm.so' for module Slurm: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190, <DATA> line 602.
 at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18.
Compilation failed in require at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
BEGIN failed--compilation aborted at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
WARNING: Logging before flag parsing goes to stderr.
W0519 13:35:16.362800 47784855040896 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-19 13:35:23,678	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_13-35-23_677955_19195/logs.
2022-05-19 13:35:23,825	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:64295 to respond...
2022-05-19 13:35:24,827	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-19 13:35:24,827	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:64295 to respond...
2022-05-19 13:35:24,939	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:30554 to respond...
2022-05-19 13:35:24,940	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-19 13:35:24,990	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_13-35-23_677955_19195/logs.
2022-05-19 13:35:24,990	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-19 13:35:24,991	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2022-05-19 13:35:25,771	INFO tune.py:65 -- Did not find checkpoint file in ./ray_mopo/HalfCheetah/halfcheetah_d3rlpy_101e3.
2022-05-19 13:35:25,771	INFO tune.py:232 -- Starting a new experiment.
W0519 13:35:25.814935 47784855040896 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0519 13:35:25.815337 47784855040896 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-19 13:35:25,920	WARNING util.py:64 -- The `start_trial` operation took 0.1393136978149414 seconds to complete, which may be a performance bottleneck.
W0519 13:46:53.047813 47784855040896 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-19 13:53:29,273	WARNING util.py:64 -- The `save_to_disk` operation took 0.940300703048706 seconds to complete, which may be a performance bottleneck.
2022-05-19 13:53:29,275	WARNING util.py:64 -- The `process_trial` operation took 0.9513862133026123 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:00:48,859	WARNING util.py:64 -- The `save_to_disk` operation took 0.4351942539215088 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:00:48,862	WARNING util.py:64 -- The `process_trial` operation took 0.44608044624328613 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:08:06,919	WARNING util.py:64 -- The `save_to_disk` operation took 0.4408855438232422 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:08:06,921	WARNING util.py:64 -- The `process_trial` operation took 0.4516923427581787 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:15:25,464	WARNING util.py:64 -- The `save_to_disk` operation took 0.4591953754425049 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:15:25,467	WARNING util.py:64 -- The `process_trial` operation took 0.47004199028015137 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:22:43,639	WARNING util.py:64 -- The `save_to_disk` operation took 0.4435279369354248 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:22:43,641	WARNING util.py:64 -- The `process_trial` operation took 0.45406007766723633 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:30:02,713	WARNING util.py:64 -- The `save_to_disk` operation took 0.4470686912536621 seconds to complete, which may be a performance bottleneck.
2022-05-19 14:30:02,715	WARNING util.py:64 -- The `process_trial` operation took 0.4579041004180908 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61401895 ON gpu-e-17 CANCELLED AT 2022-05-19T14:34:07 DUE TO TIME LIMIT ***
