Can't load '/usr/local/software/slurm/slurm-20.11.9-rhel8/lib64/perl5/auto/Slurm/Slurm.so' for module Slurm: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190, <DATA> line 602.
 at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18.
Compilation failed in require at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
BEGIN failed--compilation aborted at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
WARNING: Logging before flag parsing goes to stderr.
W0519 08:47:21.808356 47494073660288 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-19 08:47:29,194	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_08-47-29_194405_7819/logs.
2022-05-19 08:47:29,336	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:16428 to respond...
2022-05-19 08:47:30,338	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-19 08:47:30,338	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:16428 to respond...
2022-05-19 08:47:30,450	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:60097 to respond...
2022-05-19 08:47:30,451	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-19 08:47:30,489	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_08-47-29_194405_7819/logs.
2022-05-19 08:47:30,490	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-19 08:47:30,490	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0519 08:47:30.585475  7819 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2022-05-19_08-47-29_194405_7819/sockets/plasma_store, retrying 300 more times
2022-05-19 08:47:31,206	INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2022-05-19 08:47:31,206	INFO tune.py:232 -- Starting a new experiment.
W0519 08:47:31.242288 47494073660288 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0519 08:47:31.242663 47494073660288 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-19 08:47:31,354	WARNING util.py:64 -- The `start_trial` operation took 0.14082551002502441 seconds to complete, which may be a performance bottleneck.
W0519 08:55:56.403752 47494073660288 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-19 09:02:54,133	WARNING util.py:64 -- The `save_to_disk` operation took 0.9715416431427002 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:02:54,137	WARNING util.py:64 -- The `process_trial` operation took 0.9836697578430176 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:10:37,235	WARNING util.py:64 -- The `save_to_disk` operation took 0.5150754451751709 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:10:37,237	WARNING util.py:64 -- The `process_trial` operation took 0.526519775390625 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:18:20,561	WARNING util.py:64 -- The `save_to_disk` operation took 0.5114786624908447 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:18:20,563	WARNING util.py:64 -- The `process_trial` operation took 0.5227794647216797 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:26:05,986	WARNING util.py:64 -- The `save_to_disk` operation took 0.5067517757415771 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:26:05,989	WARNING util.py:64 -- The `process_trial` operation took 0.5192713737487793 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:33:49,810	WARNING util.py:64 -- The `save_to_disk` operation took 0.5190393924713135 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:33:49,813	WARNING util.py:64 -- The `process_trial` operation took 0.5314428806304932 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:41:33,516	WARNING util.py:64 -- The `save_to_disk` operation took 0.5315515995025635 seconds to complete, which may be a performance bottleneck.
2022-05-19 09:41:33,518	WARNING util.py:64 -- The `process_trial` operation took 0.5429162979125977 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61381814 ON gpu-e-17 CANCELLED AT 2022-05-19T09:45:58 DUE TO TIME LIMIT ***
