Loading rhel8/default-icl
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 intel/compilers/2020.2 intel/mkl/2020.2 intel/impi/2020.2/intel
    intel/libs/idb/2020.2 intel/libs/tbb/2020.2 intel/libs/ipp/2020.2
    intel/libs/daal/2020.2 intel/bundles/complib/2020.2
WARNING: Logging before flag parsing goes to stderr.
W0518 17:24:05.296667 23241663525760 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-18 17:24:13,100	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_17-24-13_099442_99443/logs.
2022-05-18 17:24:13,242	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:18850 to respond...
2022-05-18 17:24:14,243	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-18 17:24:14,243	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:18850 to respond...
2022-05-18 17:24:14,359	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:23071 to respond...
2022-05-18 17:24:14,359	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-18 17:24:14,411	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_17-24-13_099442_99443/logs.
2022-05-18 17:24:14,412	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-18 17:24:14,412	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0518 17:24:14.528201 99443 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2022-05-18_17-24-13_099442_99443/sockets/plasma_store, retrying 300 more times
2022-05-18 17:24:15,174	INFO tune.py:65 -- Did not find checkpoint file in ./ray_mopo/HalfCheetah/halfcheetah_mixed_capabilities_101e3.
2022-05-18 17:24:15,174	INFO tune.py:232 -- Starting a new experiment.
W0518 17:24:15.200619 23241663525760 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0518 17:24:15.200858 23241663525760 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-18 17:24:15,306	WARNING util.py:64 -- The `start_trial` operation took 0.12711119651794434 seconds to complete, which may be a performance bottleneck.
W0518 18:27:45.231199 23241663525760 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-18 18:33:39,286	WARNING util.py:64 -- The `save_to_disk` operation took 0.8249974250793457 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:33:39,290	WARNING util.py:64 -- The `process_trial` operation took 0.8336796760559082 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:34:20,946	WARNING util.py:64 -- The `process_trial` operation took 0.5257031917572021 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:35:01,088	WARNING util.py:64 -- The `process_trial` operation took 0.7640442848205566 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:40:17,925	WARNING util.py:64 -- The `save_to_disk` operation took 1.2508256435394287 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:40:17,928	WARNING util.py:64 -- The `process_trial` operation took 1.2604031562805176 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:46:48,156	WARNING util.py:64 -- The `save_to_disk` operation took 0.34555792808532715 seconds to complete, which may be a performance bottleneck.
2022-05-18 18:46:48,159	WARNING util.py:64 -- The `process_trial` operation took 0.3557775020599365 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61348627 ON cpu-q-269 CANCELLED AT 2022-05-18T18:53:10 DUE TO TIME LIMIT ***
